[book]
authors = ["peaceiris"]
language = "en"
multilingual = false
src = "src"
title = "mdbook GitHub Pages deploy with GitHub Actions"

[output.html]

# [output.linkcheck]
# follow-web-links = true
# traverse-parent-directories = false
# exclude = [ "google\\.com" ]
# user-agent = "mdbook-linkcheck-0.4.0"
# cache-timeout = 43200
# warning-policy = "warn"
