name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Read .env
        id: envs
        run: |
          . ./.env
          echo "MDBOOK_VERSION=${MDBOOK_VERSION}" | tee -a "${GITHUB_OUTPUT}"

      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '${{ steps.envs.outputs.MDBOOK_VERSION }}'

      - run: mdbook build
      - run: cd ./book && pwd && ls -la

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          cname: 'test-mdbook.peaceiris.com'
